[package]
name = "rcoin"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]

[dependencies]
curl = "0.4.8"
serde = "1.0.21"
serde_derive = "1.0"
serde_json = "1.0"
term_size = "0.3.0"
clap = "2"
chrono = "0.4"
rand = "0.4"
libc = "0.2"