[package]
name = "rcoin"
version = "0.1.0"
authors = ["Daniel Corn <info@cundd.net>"]

[dependencies]
curl = "^0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
term_size = "0.3.0"
clap = "2"
chrono = "0.4"
rand = "^0.8.5"
libc = "0.2"
